# This file is part of: APP-X11-Forward-Development-Template-Stack
# Copyright (c) 2024 Nico Jan Eelhart
#
# This source code is licensed under the MIT License found in the  'LICENSE.md' file in the root directory of this source tree.
#
         
networks: 
    x11_forward-network-fixed:  
        external: true 
        name: ext_x11_forward-network-fixed
 

volumes:
  vol_wpf:  

  
services:               
    axf-avalonia-dotnet-container:                 
        extends:
            file: ../../Base-Container/Afx-Base-Service/compose_app_forward_x11_base.yml    # Relative path to the base compose file
            service: axf-basic-service                                                   # Same service name as base file
        build:
            context: .  
            dockerfile: Docker_Avalonia-X11_Project # Docker command to execute for this compose
            args:
                PRJ_NAME_ARG: ${PRJ_NAME_ARG}       # Set PRJ_NAME_ARG with the.env file variable. Define PRJ_NAME_ARG also in Dockerfile 
                PRJ_BASE_ARG: ${PRJ_BASE_ARG}
                PRJ_TYPE_ARG: ${PRJ_TYPE_ARG}
        image: eelhart/appforwardx11-base:latest    # This name can be used to extend or chain this image.
        environment:
            - DISPLAY=host.docker.internal:0    # THIS relays the Linux output to vcxsrv(Xlaunch) Also added in the Docker file!   
                                                
        working_dir: ${PRJ_BASE_ARG}/$PRJ_NAME_ARG
        networks:
            x11_forward-network-fixed
        volumes:
            - ./shared-host:/shared-host        # Bind volume to and from our host
            - /tmp/.X11-unix:/tmp/.X11-unix     # MOUNTS the X11 socket GUI directory
        command: ["/bin/sh", "-c", "while sleep 1000; do :; done"]  # use this in case of err, let's you get in(CMD)
        
# zdocker-compose -f compose_avalonia_x11_project.yml up -d  --remove-orphans --build --force-recreate  